"""empty message

Revision ID: 68cb5c91ad95
Revises: d4272830f173
Create Date: 2022-03-22 10:34:23.675041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cb5c91ad95'
down_revision = 'd4272830f173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sets', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('data_sets', 'file_contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sets', sa.Column('file_contents', sa.VARCHAR(length=10000), nullable=True))
    op.drop_column('data_sets', 'file_path')
    # ### end Alembic commands ###
